#+TITLE: borg4platypus
#+OPTIONS: toc:nil h:1

* Purpose

Provide an Algorithm class in the Platypus framework that runs the C version of BORG under the hoods, either serially or in parallel.

* Requirements

- Python 3.6+ (sorry for that, using f-strings!)
- [[https://github.com/Project-Platypus/Platypus][Platypus]] installed in development mode (e.g. ~python -m pip install -e .~ in the cloned repo)
- [[https://github.com/uqfoundation/dill][dill]] (e.g. ~conda install dill~)
- borg.py

* Usage

- Install with
  #+BEGIN_SRC shell
  git clone XXX
  python -m pip install -e .
  #+END_SRC

* License

The MIT License (MIT)

Copyright (c) 2012-2017 Giacomo Marangoni

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
