#+TITLE: borg4platypus
#+OPTIONS: toc:nil h:1 ^:nil

* Purpose

Provide an (HACKY & EXPERIMENTAL) Algorithm class in the Platypus framework that runs the C version of BORG under the hoods, either serially or in parallel.

* Requirements

- Python 3.6+ (f-strings rock!)
- [[https://github.com/Project-Platypus/Platypus][Platypus]] installed in development mode, e.g.
  #+BEGIN_SRC shell
  git clone git@github.com:Project-Platypus/Platypus.git
  cd Platypus
  python -m pip install --user -e .
  #+END_SRC
- [[https://github.com/uqfoundation/dill][dill]] installed, e.g.
  #+BEGIN_SRC shell
  conda install dill
  #+END_SRC
- [[https://bitbucket.org/dmh309/serial-borg-moea][Serial Borg MOEA]] installed via git
  #+BEGIN_SRC shell
  git clone git@bitbucket.org:dmh309/serial-borg-moea.git
  #+END_SRC
- Path of ~borg.py~ in ~PYTHONPATH~, e.g.
  #+BEGIN_SRC shell
  export PYTHONPATH="$HOME/tools/borg/plugins/Python:$PYTHONPATH"
  #+END_SRC
  in your ~.bash_profile~.
- Path of compiled BORG libs in ~LD_LIBRARY_PATH~, e.g.
  #+BEGIN_SRC shell
  export LD_LIBRARY_PATH="$HOME/tools/borg/build/libs:$LD_LIBRARY_PATH
  #+END_SRC
  in your ~.bash_profile~.

* Installation

- Download and install this package
  #+BEGIN_SRC shell
  git clone git@github.com:jackjackk/borg4platypus.git
  cd borg4platypus
  python -m pip install --user -e .
  #+END_SRC
- Patch the Python wrapper of Serial Borg MOEA to support Python 3.6 & this lib
  #+BEGIN_SRC shell
  cd /path/to/serial-borg-moea/repo
  git am /path/to/borg4platypus/bitbucket-serial-borg-moea.patch
  #+END_SRC
- Make sure Borg works (in particular check that environmental variables are set correctly)
  #+BEGIN_SRC shell
  cd
  python -c 'from borg import Configuration;Configuration.initialize()'
  #+END_SRC

* Usage
Check ~examples/*.py~. Just use ~ExternalBorgC~ as an ~Algorithm~ class which requires an ~epsilons~ parameter (either single-valued or a list, i.e. one epsilon for each objective) after the problem argument. Whether a serial or parallel instance is launched depends on the ~mpirun~ argument.
 
* License

The MIT License (MIT)

Copyright (c) 2012-2017 Giacomo Marangoni

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
